newsmonitor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('source.urls')),
    path('', include('story.urls')),
]

source/urls.py
from django.urls import path
from . import views

app_name='source'
urlpatterns = [
path('', views.IndexView.as_view(), name='index'),
path('source/<int:pk>', views.DetailView.as_view(), name='detail'),
path('new', views.source_new, name='source_new'),
path('delete/<int:id>', views.source_del, name='source_del'),
]

story/urls.py
from django.urls import path
from . import views

app_name='story'
urlpatterns = [
# path('add/<int:id>', views.add_story, name='add_story'),
path('story/<int:id>', views.view_stories, name='story'),
path('newsfeed', views.newsfeed, name='newsfeed')
]

source/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime

class Sources(models.Model):
    title_text = models.CharField('Enter Title',max_length=200)
    pub_date = models.DateTimeField('Date Published',default=timezone.now)
    url_text = models.CharField('Enter URL',max_length=200)
    rss_text = models.CharField('Enter RSS',max_length=200)
    author_text = models.CharField('Enter Author Name',max_length=50,null=True)
    created_by = models.CharField('Created By',default=User,max_length=20,null=True)
    created_on = models.DateTimeField('Created on',default=timezone.now)

story/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from source.models import Sources
import datetime

class Story(models.Model):
    # Todo use on delete
    sources=models.ManyToManyField(Sources)
    title = models.CharField(max_length=250)
    url = models.URLField(max_length=255)
    pub_date = models.DateTimeField()
    body_text = models.TextField(null=True, blank=True)

class Meta:
    unique_together = ("url", "source")

source/forms.py
from django import forms

from .models import Sources
from story.models import Story

class SourceForm(forms.ModelForm):

    class Meta:
        model = Sources
        fields = ('title_text','pub_date','url_text','rss_text','author_text','created_by','created_on')

source/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from .models import Sources
from story.models import Story
from django.utils import timezone
from django.template import loader
from .forms import SourceForm

class IndexView(generic.ListView):
    """View to the Index Page - Sources Page"""
    model =  Sources
    template_name = 'source/index.html'
    context_object_name = 'latest_title_list'
    def get_queryset(self):
        return Sources.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:10]

class DetailView(generic.DetailView):
    """Show details of each Title"""
    model = Sources
    template_name = 'source/source.html'

def source_new(request):
    p= SourceForm(request.POST or None)
    if p.is_valid():
        p.save()
        return HttpResponseRedirect('http://localhost:8000')
    context= {'form':p}
    return render(request, 'source/form.html', context)

def source_del(request,id):
    obj = get_object_or_404(Sources, id=id)
    if request.method == "POST":
        obj.delete()
        return redirect('http://localhost:8000')
    context ={
        "obj":obj
    }
    return render(request, "source/delete.html",context)

story/views.py
import feedparser
import datetime
import dateutil.parser
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django_feedparser.settings import *
from .models import Story
from source.models import Sources
from django.utils import timezone
from django.template import loader
    #s = Story(sources=sources,title=title, url=url)

def view_stories(request, id):
    num_post = 15
        # adding stories in database
    try: 
        rss_url = Sources.objects.get(id=id).rss_text
    except Sources.DoesNotExist:
        alert("Does not Exist")
    feed = feedparser.parse(rss_url)
    for post in Story.objects.all():
        post.delete()
    story_urls = Story.objects.filter(id=id).values_list('url', flat=True)
    for entry in feed['entries']:
            url = entry.get('link')
            if url not in story_urls:
                story = Story()
                story.title = entry.get('title')
                story.url = url
                date=entry.get('published')
                story.pub_date = dateutil.parser.parse(date)
                story.body_text = entry.get('description')
                story.save()
    # passing stories data to template context and render it
    context ={
    "id":id
    }
    return render(request, 'story/story_list.html', context)
        #return render(request, "source/story_list.html")

def newsfeed(request):
    return render(request,'story/newsfeed.html')

source/templates/source/delete.html
<html>
<title>Delete | Source</title>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block content %}
<form action="" method='POST'>
{% csrf_token %}
    <h1>Do you want to delete the product"{{ obj.title_text }}"?</h1>
    <p><input type='submit' value='Yes' style="background-color: white; color: black; border: 4px solid #4CAF50;font-size: 16px; padding:10px;"/>
    <a href='../' style="background-color: white; color: black; border: 4px solid #4CAF50;font-size: 16px; padding:10px;">Cancel</a></p>
</form>
{% endblock %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

source/templates/source/form.html
<html>
<title>Enter Source | Source</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<body>
{% block content %}
<a href="http://localhost:8000" style="font-size: 22px;">Home</a>
    <h1>Add New Source</h1>
    <form method="POST" class="post-form" action="{% url 'source:source_new'%}"><h3>
        {% csrf_token %}
        {{ form.as_p }}</h3>
        <button type="submit">Save</button>
    </form>
{% endblock %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

source/templates/source/index.html
<html>
<title>Source | Homepage</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<h1 style="text-align:center;">HOMEPAGE</h1>
{% if latest_title_list %}
    <ul>
    <p><strong><h1>
    Recent Sources
    </strong></p></h1>  
   <p> <h2><a href="{% url 'source:source_new' %}" >Add New Source</a></h2>
    <h2><a href="{% url 'story:newsfeed' %}" >News Feed</a></h2></p>
<table>
  <tr>
    <th><h2>Source Title</h2></th> 
    <th><h2>Show Stories</h2></th> 
  </tr>
  {% for title in latest_title_list %}
  <tr>
    <td><h3><a href="{% url 'source:detail' title.id%}">{{ title.title_text }}</h3></a></td> 
    <td><h3><a href="{% url 'story:story' title.id %}">View</h3></a></td>
  </tr>
  {% endfor %}
</table>
{% else %}
    <h1><p>No Titles are available.</p></h1>
{% endif %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

source/templates/source/source.html
<html>
<title>Source | Details</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
    <a href="http://localhost:8000" style="font-size: 22px;">Back</a>
    <a href="{% url 'source:source_del' sources.id %}" style="font-size: 22px; text-align: right">Delete</a>
<h1>{{ sources.title_text }}</h1>
<ul>
    <li><h3>URL : <a href="{{ sources.url_text }}">{{ sources.url_text }}</a></h3></li>
    <li><h3>RSS File: <a href="{{ sources.rss_text }}">{{ sources.rss_text }}</a></h3></li>
    <li><h3>Author by: {{sources.author_text}}</h3></li>
    <li><h3>Created by: {{sources.created_by}}</h3></li>
    <li><h3>Created on: {{sources.created_on}}</h3></li>
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

story/templates/story/newsfeed.html
<html>
<title>Source | News Feed</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
{% load custom_tags %}
{% with story=600|story %}
    <a href="http://localhost:8000" style="font-size: 22px;">Back</a>
{% if story %}
<h1>Newsfeed | All news in one place</h1>
{% for post in story %}
<h3>Title : <a href="{{ post.url }}">{{ post.title }}</a></h3>
<h3>Published on: {{post.pub_date}}</h3>
<br>
{% endfor %}
{% else %}
    <h1>Sorry, no Post in this list.</h1>
{% endif%}
{% endwith %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>

story/templates/story/story_list.html
<html>
<title>Source | Stories</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'source/style.css' %}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
{% load custom_tags %}
{% with story=150|story %}
    <a href="http://localhost:8000" style="font-size: 22px;">Back</a>
{% if story %}
<h1>Latest stories.</h1>
{% for post in story %}
<h2>TITLE: {{ post.title }}</h2>
<h3>URL : <a href="{{ post.url }}">{{ post.url }}</a></h3>
<h3>Published on: {{post.pub_date}}</h3>
<h4>Description: {{post.body_text}}</h4><br><br>
{% endfor %}
{% else %}
    <h1>Sorry, no Post in this list.</h1>
{% endif%}
{% endwith %}
</body>
<div>
<footer> Made with &hearts; by Arpit</footer>
</div>
</html>